# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely edit after that. If you find
# yourself editing these this file very often, consider using Jekyll's data files
# feature for the data you need to update frequently.
#
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'bundle exec jekyll serve'. If you change this file, please restart the server process.

# Site settings
# These are used to personalize your new site. If you look in the HTML files,
# you will see them accessed via {{ site.title }}, {{ site.email }}, and so on.
# You can create any custom variable you would like, and they will be accessible
# in the templates via {{ site.myvariable }}.
title: Dmytro Kalpakchi
tagline: Has occasionally interesting thoughts
email: dkalpackchi
description: > # this means to ignore newlines until "baseurl:"
  A personal website of Dmytro Kalpakchi with occasionally interesting thoughts.
baseurl: "" # the subpath of your site, e.g. /blog
url: "https://dkalpakchi.github.io" # the base hostname & protocol for your site, e.g. http://example.com

github:
  username: dkalpakchi

social:
  name: Dmytro Kalpakchi
  email: dmytroka@kth.se

permalink: /:title/

excerpt_separator: <!--more-->

avatar: /assets/img/logo.png

# Build settings
markdown: kramdown
highlighter: rouge
theme: jekyll-theme-chirpy
gems:
  - jekyll-feed
  - jemoji
  - jekyll-redirect-from
exclude:
  - Gemfile
  - Gemfile.lock

collections:
  tabs:
    output: true
    sort_by: order

jekyll-archives:
  enabled: [categories, tags]
  layouts:
    category: category
    tag: tag
  permalinks:
    tag: /tags/:name/
    category: /categories/:name/

defaults:
  -
    scope:
      path: ''          # An empty string here means all files in the project
      type: posts
    values:
      layout: post
      comments: true    # Enable comments in posts.
      toc: true         # Display TOC column in posts.
      # DO NOT modify the following parameter unless you are confident enough
      # to update the code of all other post links in this project.
      permalink: /posts/:title/
  -
    scope:
      path: _drafts
    values:
      comments: false
  -
    scope:
      path: ''
      type: tabs             # see `site.collections`
    values:
      layout: page
      permalink: /:title/
      dynamic_title: true    # Hide title in mobile screens.

# direct translation
default_lang: 'en'
languages: ['en', 'uk']
i18n:
  en:
    panel:
      trending_tags: Trending Tags
      lastmod: Recent Update
    posts:
      posted_on: posted on
      in_category: in category
      tagged_by: tagged by
      further_reading: Further Reading
      share: Share
    menu:
      posts: Posts
      sandbox: Scientific sandbox
      projects: Educational projects
      about: About me
      lang: In English
      language: Language
      title: Dmytro Kalpakchi blog
    categories:
      thoughts: thoughts
      en: In English
      education: education
    tags:
      welcome: welcome
      hello: hello
      education: education
      ukraine: Ukraine
      sweden: Sweden
      higher-education: higher education
    dates:
      Jan: Jan
      Feb: Feb
      Mar: Mar
      Apr: Apr
      May: May
      Jun: Jun
      Jul: Jul
      Aug: Aug
      Sep: Sep
      Oct: Oct
      Nov: Nov
      Dec: Dec
    util:
      on: on
      updated: Updated
      copy_link: Copy link
  uk:
    panel:
      trending_tags: Популярні теги
      lastmod: Останні оновлення
    posts:
      posted_on: опубліковано
      in_category: у категорії
      tagged_by: із позначками
      further_reading: Може бути цікаво
      share: Поділитися
    menu:
      posts: Дописи
      sandbox: Наукова пісочниця
      projects: Освітні проекти
      about: Про мене
      lang: Українською
      language: Мова
      title: Блог Дмитра Калпакчі
    categories:
      thoughts: роздуми
      uk: Українською
      education: освіта
    tags:
      welcome: вітання
      hello: привіт
      education: освіта
      higher-education: вища освіта
      ukraine: Україна
      sweden: Швеція
    dates:
      Jan: Січ
      Feb: Лют
      Mar: Бер
      Apr: Кві
      May: Тра
      Jun: Чер
      Jul: Лип
      Aug: Серп
      Sep: Вер
      Oct: Жов
      Nov: Лис
      Dec: Гру
    util:
      on: на
      updated: Оновлено
      copy_link: Скопіювати посилання
